### ISSUE TITLE
Make PR title/body customisable

### ISSUE THREAD

**Issue by JonasJurczok** [vsoch/pull-request-action#1]
Hi,
I really like this action and learned a lot from it.

What prevents me from using it is that you cannot overwrite the PR title/body.

Unfortunately I don't have the time right now to create a PR myself.

**Comment by vsoch** [comment]
hey no worries, and glad to hear that you like it! I’ll see if I can make some time to tweak it.

**Comment by JonasJurczok** [comment]
Awesome thanks :)

**Comment by vsoch** [comment]
hey @JonasJurczok ! I just opened a PR here  -> https://github.com/vsoch/pull-request-action/pull/3 would you care to review? If it looks good I can merge and then you can test in the wild.

**Comment by vsoch** [comment]
Issue resolved yesterday with #3 closing.
