### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType 

### ISSUE THREAD

**Issue by yanhong-tech** [vsoch/pull-request-action#101]
While using “/pull-request-action@master” actions. The action created the pull request but threw an error made a steps red. The error shows; 

File “/pull-request.py”, line 83, in set_env_and_output
  with open(environment_file_path, “a”) as environment_file: 

TypeError: expected str, bytes or os.PathLike object, not NoneType. 

GitHub env and the actions passed env are all string. Can you help check this error showed up? Thanks!

**Comment by vsoch** [comment]
It sounds like the `environment_file_path` is set to None, so one of these two is set to None:

https://github.com/vsoch/pull-request-action/blob/0969c26295afdeffaab628fee287a98b27eca529/pull-request.py#L79-L84

Can you tell me if you can see which variable it's choking on? Or if those envars have changed? Likely if one is unset we can just check for None (and not set it there) but it GitHub actions has changed that variable we need to do more updates.

**Comment by vsoch** [comment]
Try testing with this branch - let me know which is reported unset https://github.com/vsoch/pull-request-action/pull/102

**Comment by yanhong-tech** [comment]
I cannot see which one got choking on.  
I think we only made pull @master, but let me try. Thanks for checking thought!

**Comment by vsoch** [comment]
If you try the PR branch I linked it should print the one that is None. Thank you!

**Comment by yanhong-tech** [comment]
when I use my personal repo, this action all works. I need get the access for the repo(only sync master) I had error to pull your branch to test. will let you know! Thank you.

**Comment by vsoch** [comment]
You shouldn't need to pull my branch - just change the URI of the action in your workflow file, instead of `@master` do `@test-envar-files` and it will use the branch.

**Comment by yanhong-tech** [comment]
yes that's how I did the test, it works on my own repo, but enterprise repo i am working on we have the middle network control that i can not pull @test-envar-files test branch.

**Comment by vsoch** [comment]
Sorry not sure I can help with advice for how to test enterprise. Maybe use a free account?

**Comment by yanhong-tech** [comment]
Hi vsoch, sorry get back a little bit late. Finally this test can go though by using @test-envar-files branch. The job is green from your change. and it has the warning that `Warning: GITHUB_OUTPUT is unset, skipping.`.  we usually not set GITHUB_OUTPUT. Let me know if you plan to merge your conditions or I can set this variable. Thanks

**Comment by vsoch** [comment]
@yanhong-tech thanks for the update! I think that's probably OK - that sounds like it might be a change or depend on the environment. Let's merge and release to master.

**Comment by vsoch** [comment]
All set and merged / releases, version 1.1.1. Thanks!
