### ISSUE TITLE
Unable to retrieve information about pull requests: 403: Forbidden

### ISSUE THREAD

**Issue by ahmadmssm** [vsoch/pull-request-action#103]
Hi,
The action was working before but now I have this issue.
`{'message': 'Resource not accessible by integration', 'documentation_url': 'https://docs.github.com/rest/pulls/pulls#list-pull-requests'}`

**Comment by vsoch** [comment]
Nothing has changed here. Reading that link what would you like me to try?

**Comment by ahmadmssm** [comment]
The problem is that the terminal is not showing anything useful, and as I mentioned it was fine and suddenly stopped working.

**Comment by ahmadmssm** [comment]
It was an issue with GitHub permissions.

**Comment by vsoch** [comment]
Yeah I was about to suggest that :) https://github.com/orgs/community/discussions/60820 Glad you got it figured out!
