### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by mzahlan** [vsoch/pull-request-action#18]
what is this line uses: vsoch/pull-request-action@master

what should i put here please help

**Comment by vsoch** [comment]
That line is in reference to using the action here. If you look at the [example in the README](https://github.com/vsoch/pull-request-action) you can start with that and modify. If you aren't familiar with GitHub actions, you should probably [read about them first](https://help.github.com/en/actions).

**Comment by vsoch** [comment]
No follow up, closing issue.
