### ISSUE TITLE
Allow for assigning reviewers (individuals and teams)

### ISSUE THREAD

**Issue by vsoch** [vsoch/pull-request-action#25]
Per discussion in #23 and #19 we would want to add integration with this API endpoint https://developer.github.com/v3/pulls/review_requests/ to either assign an individual or team as reviewer. @satishjuvo88 if I can make some time to implement this, would you again be able to test?

**Comment by vsoch** [comment]
All set, please test / review https://github.com/vsoch/pull-request-action/pull/26.

**Comment by satishjuvo88** [comment]
@vsoch i'll do it now thanks

**Comment by satishjuvo88** [comment]
It doesnt work for me, not sure if im doing something wrong.


          
> PULL_REQUEST_REVIEWERS: 'akaroth'
          PULL_REQUEST_TEAM_REVIEWERS: 'juvoinc/webteam'

**Comment by vsoch** [comment]
Can you share the print output in your action?

**Comment by satishjuvo88** [comment]
"href": "https://api.github.com/repos/***inc/***-admin-panels/statuses/9aa41cc528ce13eb4c920b1a17d079471b67cb5b"
    }
  },
  "author_association": "NONE",
  "merged": false,
  "mergeable": null,
  "rebaseable": null,
  "mergeable_state": "unknown",
  "merged_by": null,
  "comments": 0,
  "review_comments": 0,
  "maintainer_can_modify": false,
  "commits": 5,
  "additions": 4,
  "deletions": 2,
  "changed_files": 1
}
Number opened for PR is 122
Found reviewers: "akaroth" and team reviewers: "***inc/webteam"
{"reviewers":["akaroth"], "team_reviewers":["***inc"/,"webteam"]}
Enter host password for user 'satish***88':
{
  "message": "Problems parsing JSON",
  "documentation_url": "https://developer.github.com/v3/pulls/review_requests/#create-a-review-request"
}
0
==========================================================================
END: Finished

**Comment by vsoch** [comment]
The names of the team I don’t think should have a slash. Why did you include the slash? Can you show me a link to the team?

**Comment by vsoch** [comment]
hey @satishjuvo88 just to follow up - you don't need to specify the organization (I noticed that it's an org here https://github.com/juvoinc/) with the team, it's implied that the team being assigned to the PR needs to be in the same organization as the repository. I've tested this locally so I'm going to merge and then release, and please re-open an issue if you still have an issue after removing the team name and `/` from the action workflow. Thanks!
