### ISSUE TITLE
Team Reviewers doesnt work

### ISSUE THREAD

**Issue by satishjuvo88** [vsoch/pull-request-action#29]
As per your advice, i removed the org name and the '/ and tried and also individual reviewers also dont work.

> Number opened for PR is 125
Found reviewers: "akaroth" and team reviewers: "webteam"
{"reviewers":["akaroth"], "team_reviewers":["webteam"]}
Enter host password for user 'satish***88':
{
  "message": "Validation Failed",
  "errors": [
    "Could not resolve to a node with the global id of 'MDQ6VGVhbTMyNzAxOTA='."
  ],
  "documentation_url": "https://developer.github.com/v3/pulls/review_requests/#create-a-review-request"
}
Add reviewers return code: 0
==========================================================================
END: Finished

I got this error message again, not sure what is means

**Comment by vsoch** [comment]
This looks like a permissions issue https://github.com/probot/probot/issues/981 so it’s either a permission missing or the team is private.
