### ISSUE TITLE
Actions for an opened PR don't seem to execute

### ISSUE THREAD

**Issue by jsquyres** [vsoch/pull-request-action#30]
Greetings, and thanks for pull-request-action!

In my project, we write / maintain Linux man pages in Markdown files.  When we merge pull requests containing changes to those Markdown files, an automated process runs `pandoc` on them to generate corresponding nroff man pages, and then opens a new pull request to commit those generated nroff pages.  Once the CI completes, the PR is automatically merged.

We have some existing krufty scripting to do this workflow.  I was poking around with Github Actions this weekend to see if I could migrate away from our krufty scripts.

Your action seems perfect!  Here's the workflow I would like to do:

1. Developer creates a pull request with changes to a markdown file (e.g., `fabric.7.md`).
1. When that PR is merged, some processing occurs on that changed `.md` file, and generates new nroff files (i.e., man pages).
1. If there were, indeed, changes to the generated nroff files:
    1. git commit them
    1. push them to a branch back up in the github repo (e.g., `md2nroff/from-[SHA]`)
    1. make a pull request from that branch to `master`
    1. put the `automerge` label on that PR
1. when the CI completes on that PR, merge it

Just about everything works in my test repo: https://github.com/jsquyres/test-pandoc-stuff

_Except_ that when `pull-request-action` creates a pull request, the trivial (fake) CI that I have defined in https://github.com/jsquyres/test-pandoc-stuff/blob/master/.github/workflows/ci.yml does not automatically run.  This prevents the next step in the workflow from firing (i.e., automatically merge PR's when they are ready -- defined here: https://github.com/jsquyres/test-pandoc-stuff/blob/master/.github/workflows/automerge_completed_pull_requests.yml).

What I don't understand is that `ci.yml` runs properly when I manually create a PR.  But when `pull-request-action` creates a PR, `ci.yml` does not run.  This is odd, because `ci.yml` contains:

```yaml
on: pull_request
````

which, according to https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request, should run the jobs in this file when a PR is `opened`, `synchronize`, or `reopened`.

Here's an example on the repo that I cited above:

1. PR where I made changes to `fabric.7.md`: https://github.com/jsquyres/test-pandoc-stuff/pull/16
1. PR that was automatically created when https://github.com/jsquyres/test-pandoc-stuff/pull/16 was merged: https://github.com/jsquyres/test-pandoc-stuff/pull/17

You can see that 17 is stuck in the state waiting for the required "ci" check to run.  But if you look in the "Actions" tab, it did not run for PR 17.

Do you have any idea why `ci.yml` wouldn't run on a PR opened by `pull-request-action`?

Thanks!

**Comment by vsoch** [comment]
It's a hard rule that actions cannot trigger other actions. So if an action creates a pull request, other actions cannot be triggered from it. What I usually try to do is represent (to the greatest extent possible) all steps of the workflow in one file, and avoid actions trying to trigger other actions (which never will work).

**Comment by vsoch** [comment]
See https://github.community/t5/GitHub-Actions/Triggering-a-new-workflow-from-another-workflow/td-p/31676

**Comment by jsquyres** [comment]
@vsoch Ah, that explains it.  Many thanks for the pointer!

FWIW: I might have to go the bot user / custom token route, because our CI can take upwards of an hour -- far too long for a single Action job to wait to merge the PR.

**Comment by vsoch** [comment]
Good luck! I also ran into this issue when I started using actions and was fairly bummed :) if you need layers of CI you could try interacting with Travis or Circle via API from an action, or triggering them separately instead... I don’t think they can know if a PR is opened by a bot. So either of those could work!

**Comment by dogmatic69** [comment]
I've created a hack that closes and reopens a PR which triggers the CI to run. Using a PAT for creating PRs is not a good idea with a user token as that user will not be able to approve the PR nor make any change requests.

With my hack you can use the github token to create the PR and a PAT token to do the close/open dance.

https://github.com/dogmatic69/actions/blob/master/.github/workflows/automation-pr.yml#L50-L54

**Comment by vsoch** [comment]
How should we address this?

**Comment by dogmatic69** [comment]
Don't think you can do anything about it for now. The problem is not that actions cant trigger other actions, instead the GITHUB_TOKEN cant be used to trigger actions. The workaround I've posted above will allow this to work until github removes this limitation.

For reference this is possible on gitlab. Perhaps when github sees workarounds like this they will remove the limitation. (I guess they are trying to protect from circular triggers).
