### ISSUE TITLE
Update pull request

### ISSUE THREAD

**Issue by Benoss** [vsoch/pull-request-action#34]
I see that in your code you return if the pull request already exists.

My use case is to open and a pull request from master to branch prod and I would like to auto update the description of this pull request with the list of pull requests that have been merge into master since the last merge of master into prod'
God this looks complicated said like this.

Workflow
Merge pull request 13 from feature1 branch to master -> Create pull request 14 from master to prod with a description like
```
## Pull request created at {date} to release to prod

## Features Merged
#14 Feature1
```
Merge pull request 14 from feature2 branch to master -> Update pull request 14  with something like
```
## Pull request created at {date} to release to prod
Added description by the user

## Features Merged
#14 Feature1
#15 Feature2
```

Obviously I would need to add a line at the end of the description or split the body on "## Features Merged" to reconstruct the list
Does it makes sense to you?

**Comment by vsoch** [comment]
hey @Benoss - if you open a PR and push any changes to that branch, that alone will update the PR. I would suggest taking an approach that is less hard coding in some specific action for your use case, and more putting together steps like modular pieces. More specifically, given some variable set by pull request action, you instead comment again on the PR. E.g., [modify this recipe](https://github.com/vsoch/pull-request-action/blob/master/examples/outputs-example.yml) to check the return codes and then act accordingly. If you want to set up a recipe like that and then show the various outputs, what we might need to update is making sure that the PR number for the existing PR is returned. Please give that a start and then link me to the running action and we can go from there.

**Comment by Benoss** [comment]
Yeah I realise that's a bit complex, first step is probably just a variable to allow updates :)

**Comment by vsoch** [comment]
Sorry I think you are misunderstanding - given that a PR is already open, if you just push again to that branch, the PR is updated. There is no special action needed on the part of the action here if the PR is already open :) If you, however, want to post an additional comment, I'd suggest setting up a recipe as I suggested, printing out those output variables, and then if something is missing we can add it. But I think you should be able to just parse them, determine based on the exit code that it's open, and then post a comment. See snakemake for an example of doing this - it posts a comment on the PR based on needing black formatting.

https://github.com/snakemake/snakemake/blob/master/.github/workflows/main.yml#L25

You would want a similar thing, but have the if condition triggered based on the PR already being open (the status code) and the number (the pr number).

**Comment by Benoss** [comment]
The other thing that would be good is to be able to set the the author of the PR to the person that pushed. Also be able to use an existing pull request template in the repo if exists

**Comment by vsoch** [comment]
The author is likely available as a variable in the GitHub payload, and environment inputs already are defined to add assignees, reviewers, or team reviewers, so you should already be able to do this. If you need a custom message or title, just set those as envars too. I’m not sure anymore what you are asking for development or feature or help wise, so I’m going to close the issue. If/when you implement something and have an actual use case that we can debug, happy to help again.
