### ISSUE TITLE
set-env is being deprecated

### ISSUE THREAD

**Issue by vsoch** [vsoch/pull-request-action#49]
See https://github.com/vsoch/pull-request-action/pull/48 for a potential fix. We can work on this when it's needed for some user.

**Comment by bakkerthehacker** [comment]
set-env has now been disabled entirely and this action no longer works

**Comment by vsoch** [comment]
A PR was actually merged about 30 minutes ago so this is no longer an issue, and now it's a release. https://github.com/vsoch/pull-request-action/releases/tag/1.0.12 Cheers!
