### ISSUE TITLE
Please create `v1` tag or branch

### ISSUE THREAD

**Issue by AlekSi** [vsoch/pull-request-action#55]
So people can depend on `vsoch/pull-request-action@v1`

https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/about-actions#using-release-management-for-actions

**Comment by vsoch** [comment]
We have releases for each version... can you clarify what you want?

**Comment by AlekSi** [comment]
I want to be able to depend on `vsoch/pull-request-action@v1` instead of `@1.m.p` and update it with each patch release. Providing `v1` tag or branch is the recommended best practice. Please read the link.

**Comment by vsoch** [comment]
I'm not sure I agree with this suggested practice (it's akin to a latest container, a moving target) but I'm happy to create a branch for you https://github.com/vsoch/pull-request-action/tree/v1. Cheers!

**Comment by AlekSi** [comment]
Thank you. I too don't agree with that "floating" tag, but unfortunately, that's how most other actions work. If `v1` branch always points to the latest release / tag, it should work the same for GitHub Actions, and does not require force pushes.

Thank you again!
