### ISSUE TITLE
Action fails when no diff between branches

### ISSUE THREAD

**Issue by DavideViolante** [vsoch/pull-request-action#56]
It's normal that the action fails when there are no differences between the branches?
I'd expect a fail when the action should actually open the PR, but it doesn't.

The error I get is
```
Unable to create pull request: 422: Unprocessable Entity, Validation Failed
```

That is not much clear about the reason of the failure.

**Comment by vsoch** [comment]
This actually happened to me recently because I was trying to open a PR for a branch that didn't exist, and you're right, the message is a bit cryptic. Let me take a look and see if I can make it more verbose.

**Comment by vsoch** [comment]
okay, I have a branch for you to test!

https://github.com/vsoch/pull-request-action/pull/57

If you can reproduce the issue above, that would be great! See the description in the PR for an explanation of changes. And let me know if/when it works, and show me a screenshot / link to the action to confirm.

**Comment by DavideViolante** [comment]
Just tested it:
![vsochautopr](https://user-images.githubusercontent.com/6844116/101982633-a9a5fd00-3c75-11eb-925b-358d3851a68d.png)

The action still fails, but with a better message.
How can I make it pass in this case?

**Comment by vsoch** [comment]
You don’t have any changed commits, so there is nothing to PR. You’d want to checkout a new branch, make changes, push, then use the action.

**Comment by vsoch** [comment]
@DavideViolante if you get a chance, could you please review / approve the PR so that the default has this improved verbosity?

**Comment by DavideViolante** [comment]
> You don’t have any changed commits, so there is nothing to PR. You’d want to checkout a new branch, make changes, push, then use the action.

I know... but I'd expect that the action would not **fail** in this case. The action executed correctly, it checked that no PR is needed, and it finishes.
I run this on a cron basis, such as every monday. If there are no diff between 2 branches, I expect no PR, and no fail from the action (it worked correctly).

**Comment by vsoch** [comment]
Ah I see, then I think you would want to set `PASS_ON_ERROR` (see the README).

**Comment by DavideViolante** [comment]
Yeah it would be a solution, but I think **by default**, if the PR should not be created coz there are no diff, or coz it's already opened, there should be no fail for the action.

Thanks anyway, it's just my opinion, there is no right solution, it more UX perception than a bug.

**Comment by vsoch** [comment]
hey @DavideViolante sorry I gave you the wrong environment variable! You can set `PASS_IF_EXISTS` to get the specific functionality you are looking for. It's not the default because different users would have different preferences. Hope that helps!

**Comment by steven-prybylynskyi** [comment]
`PASS_IF_EXISTS` is:
> Instead of failing if the pull request already exists, pass

For this situation a new variable is needed, e.g. `PASS_IF_NO_DIFF`

**Comment by vsoch** [comment]
Yep would be open to a PR to add this, if desired.
