### ISSUE TITLE
Pull request title is always "is"

### ISSUE THREAD

**Issue by bencooper222** [vsoch/pull-request-action#6]
No matter if I set the PR title myself or let it be the default (which should be the update container string), the title is always "is".

**Comment by vsoch** [comment]
I think it's likely there are missing quotes, [the default](https://raw.githubusercontent.com/singularityhub/registry-org/master/.github/main.workflow) does work, and see the pull requests [here](https://github.com/singularityhub/registry-org/pulls?q=is%3Apr+is%3Aclosed). Could you share your workflow file?

**Comment by vsoch** [comment]
I just added quotes, could you look in your action and see what it's echoing for the data? Should coincide with this line:

```
echo "curl --user ${GITHUB_ACTOR} -X POST --data ${DATA} ${PULLS_URL}"
```

**Comment by vsoch** [comment]
See https://github.com/vsoch/pull-request-action/issues/7, this has been fixed.
