### ISSUE TITLE
Variable `assignees` referenced before assignment

### ISSUE THREAD

**Issue by i077** [vsoch/pull-request-action#64]
I'm running the latest release of this action. See [this log](https://github.com/i077/system/runs/1904761591?check_suite_focus=true#step:8:69) for an example.

Maybe you forgot to pass in the `assignees` parameter in [line 323](https://github.com/vsoch/pull-request-action/blob/master/pull-request.py#L323)?

**Comment by vsoch** [comment]
You're totally right - I'll get a PR in asap!

**Comment by vsoch** [comment]
Here is a branch to test! As soon as you confirm it fixes the above, we can merge and release:

https://github.com/vsoch/pull-request-action/pull/65

Apologies for the oversight, and thank you for reporting the issue!

**Comment by i077** [comment]
Thanks for the quick response!

Uhh, quick question: how do I tell GitHub Actions to use a certain branch for the action?

**Comment by i077** [comment]
Welp, nvm. Found it [here](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions): 

> Specifying a target branch for the action means it will always run the version currently on that branch.

**Comment by vsoch** [comment]
When you are specifying the action name, instead of master or a version tag, just specify the branch. E.g.,:

```yaml
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@add/assignees-bck
```

You are too speedy for me! :)

**Comment by i077** [comment]
[Looks like that fixed it](https://github.com/i077/system/runs/1905322206?check_suite_focus=true)!

**Comment by vsoch** [comment]
Woohoo! Let's get this released asap, thank so so much for catching the bug! I refactored the one major function into smaller ones and clearly just missed that.
