### ISSUE TITLE
Error: The `set-env` command is disabled.

### ISSUE THREAD

**Issue by raelriolinozup** [vsoch/pull-request-action#66]
It seems that the outputs are triggering an error on my environment. The Pull Request is actually created, but the action fails when trying to set the outputs. Since i don´t have permission to change my repository config, is it possible to disable this outputs?

### Full error message:

Error: Unable to process command '::set-env name=PULL_REQUEST_NUMBER::4' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::set-env name=PULL_REQUEST_RETURN_CODE::0' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::set-env name=PULL_REQUEST_URL::https://github.com/raelriolinozup/changelog-test/pull/4' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by vsoch** [comment]
We only have that in older versions. What version are you using?

**Comment by raelriolinozup** [comment]
I was using version 1.0.6.... But i ended up creating a custom script to post the pull request in node... As a sugestion, maybe it could be a good idea to have an option to toggle the output step for some one else that may face the same issue as mine. =)

**Comment by vsoch** [comment]
That's an old version - the newer versions don't have this issue. https://github.com/vsoch/pull-request-action/releases/tag/1.0.15. The good idea is to use a more recent version. :)

**Comment by flavio-fernandes** [comment]
> That's an old version - the newer versions don't have this issue. https://github.com/vsoch/pull-request-action/releases/tag/1.0.15. The good idea is to use a more recent version. :)

I think a source for this confusion is because your examples / doc may still be referring to old versions.
Example (line 23 of README.md):

https://github.com/vsoch/pull-request-action/blob/7f0d383d15d48df0e5dc744596f4b9057f67e4c4/README.md#L23

Maybe a way to close this issue is to have them pointing to the latest release.
And THANK YOU for this awesome action!

**Comment by vsoch** [comment]
That's a great idea! I'll update that to point to master, with a comment to use a specific release. Would that work?

**Comment by vsoch** [comment]
See https://github.com/vsoch/pull-request-action/pull/67

**Comment by vsoch** [comment]
I think this was resolved, closing issue. Thanks again!
