### ISSUE TITLE
PR body is blank

### ISSUE THREAD

**Issue by bencooper222** [vsoch/pull-request-action#7]
Currently, body isn't included in the stuff that gets POSTed to the GitHub API. Even if we fix it, I have a similar issue to the last error where only the first word in the body is sent. I think the solution to this issue or #6 is to either use jq (full disclosure: this is based on one [google search](https://stackoverflow.com/questions/43373176/store-json-directly-in-bash-script-with-variables)) in the shell or switch to a more expressive language like JS. Personally, I think the latter would make this more maintainable but jq would probably work

**Comment by vsoch** [comment]
How would jq help? It's meant to parse json output, not post.

I've successfully used [python](https://github.com/vsoch/confucious-actions/blob/master/pull_request_fail/post_message.py) to read in a file and then send with requests, this might be a more reasonable idea so the user doesn't need to think about how to escape the envar. We could change the post to be done in a similar way, would that work?

**Comment by bencooper222** [comment]
My impression was jq could help compose json - looks like I was wrong. 

I think that would work? I'm not really an expert on shell files but that sounds reasonable.

**Comment by vsoch** [comment]
I won't be able to take a look until tomorrow, but in the meantime could you please share your main.workflow and the output from the log in your Google action? I will need it to debug further.

**Comment by bencooper222** [comment]
https://github.com/VandyHacks/fisherman/runs/132861567

It's all in that repo. Note that I slightly altered the version of the action that that repo runs: https://github.com/bencooper222/pull-request-action/commit/72248aa34f85ae3b74f1862fb5811cb8d87cfb62

**Comment by vsoch** [comment]
All fixed :) See the PR here https://github.com/vsoch/pull-request-action-test/pull/3 and the associated workflow for that repo:

```
workflow "Create Pull Request" {
  on = "push"
  resolves = "Create New Pull Request"
}

action "Create New Pull Request" {
  uses = "vsoch/pull-request-action@master"
  secrets = [
    "GITHUB_TOKEN"
  ]
  env = {
    PULL_REQUEST_BRANCH = "master"
    PULL_REQUEST_DRAFT = "true"
    PULL_REQUEST_TITLE = "This is the title of the PR"
    PULL_REQUEST_BODY = "This is the body of the PR"
  }
}
```
The body was missing from the data, and quotes fixed the missing title, etc.

**Comment by bencooper222** [comment]
Thanks!
