### ISSUE TITLE
Use repo default branch instead of hard-coded "master"

### ISSUE THREAD

**Issue by dannysauer** [vsoch/pull-request-action#74]
https://github.com/vsoch/pull-request-action/blob/1cb1956a68e7d8b6bf693d41299467bb0f1b6a7a/pull-request.py#L347

It probably makes sense to use the relevant API call to fetch the default branch of a repo instead of hard-coding in "master" here.  Github [made the change](https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/) last year, and the way to get the value in a shell is
```shell
curl -L -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/${owner}/${repo} \
            | jq .default_branch
```

That should be pretty straightforward to translate into Python.  I'll open a PR when I find a few spare minutes if no one else does it first.

**Comment by vsoch** [comment]
That's a great idea! Yes, would gladly accept a PR for this update. Thank you @dannysauer !
