### ISSUE TITLE
Allow to customize github url

### ISSUE THREAD

**Issue by sta-szek** [vsoch/pull-request-action#77]
hi, i would like to use that action with private GHES, can we customize url? instead of github.com i would like to use mygithub.mysite.com

**Comment by vsoch** [comment]
Yes I can take a shot to develop that for you. Can you show me an example of another GitHub action that is setup to work with private GHES so I can become familiar?

**Comment by sta-szek** [comment]
> Yes I can take a shot to develop that for you. Can you show me an example of another GitHub action that is setup to work with private GHES so I can become familiar?

sorry for long replay, i am not watching notifications as working on GHES.

example: https://github.com/CodelyTV/pr-size-labeler

**Comment by vsoch** [comment]
okay here is a branch to test! https://github.com/vsoch/pull-request-action/pull/80 The branch is called `add/github-enterprise-url` that you can specify to use for the action, and the envar to set is `PULL_REQUEST_API_URL` which will default to https://api.github.com and can be set to a custom enterprise URL.

**Comment by sta-szek** [comment]
unfortunately we cannot use this branch as we cannot use actions from public. we can use only synchronized-master branches.
i hope somebody else will be able to test it so it can be merged.
thanks for the effort @vsoch 👍 🙇

**Comment by vsoch** [comment]
@sta-szek this is a fairly small change - if I merge to the master/main branch would you be able to test promptly? When you confirm working I'll do a release (and if not we can revert pretty easily).
