### ISSUE TITLE
AutoMerge via GraphQL mutation?

### ISSUE THREAD

**Issue by falconmick** [vsoch/pull-request-action#78]
Ahoy @vsoch  thought I would make a separate issue for this, less of an issue more of an idea.

Have you done any looking into enabling auto merge? Theoretically you could just manually form the GraphQL query and just use post like you currently are doing, basically it would be a more conviluted POST request with a weird body instead of a bog standard POST call like you already have. https://docs.github.com/en/graphql/guides/forming-calls-with-graphql

It appears that there isn't a plain ole boring API endpoint for this and it's not a parameter on the Create Pull Request API endpoint unfortunately. I would try to form this as a PR so I could show an example of how it could look but I've never done python and I wouldn't know where to start

the API reference is here:
https://docs.github.com/en/graphql/reference/mutations#enablepullrequestautomerge

**Comment by vsoch** [comment]
That’s a interesting idea. My personal opinion on the matter is that auto merge is something that can be enabled on the level of the repository, once, and should have thought put into that decision and not dictated by an automated action. From a functional standpoint, if someone wants auto merge they can enable it regardless of any particular workflow, and if they really just want to skip the PR any changes could be pushed directly to the intended branch. So I don’t see a strong use case for the action here, but it would be interesting to think about cases when this would be desirable to be automated.

**Comment by falconmick** [comment]
Unless I’m wrong (wouldn’t be first time) the auto merge option just adds a new merge option on PR’s that will once clicked merge the PR after all checks complete. I’m yet to find a way to instruct GitHub to automatically merge prs without any interaction on my behalf. The linked mutation is equivalent to clicking that manual auto merge button that shows up when you’ve enabled the feature
