### ISSUE TITLE
Check for pull request might use grep

### ISSUE THREAD

**Issue by vsoch** [vsoch/pull-request-action#9]
The current implementation checks for an error code, but noted in https://github.com/vsoch/pull-request-action/pull/8#issuecomment-524256043 the error code will still be 0 when a message is returned that the request already exists. A better strategy would be to grep the message (or something similar) to see that it already exists.

**Comment by chancancode** [comment]
To clarify, I don’t really know what the curl exit code is when the server returns a failure, so someone should double check. I was just saying that, as a whole, our bash function and bash script seems to be return cleanly so GittHub assumed it passed when it didn’t.
